# Generated by Django 4.0.4 on 2022-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0002_alter_game_estimated_time_to_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', through='raterapp.GameCategories', to='raterapp.category'),
        ),
    ]
